### ISSUE TITLE
Extra topic added to entity upon edit

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-local#187] opened 2015-03-26 17:40 UTC
Using the webui, if the topic, "442 Regimental Combat Team [89]" is present in an entity, the topic, "Women's Army Corps/Women's Army Auxiliary ​Corps [442]" will be automatically added when the entity is brought into edit mode. It is possible to manually delete the extra topic before saving the edit.

May be due to the parser in the tagging UI.

**Comment by gjost** [comment] 2015-03-26 17:57
Affected
* 442 Regimental Combat Team [89]
* September 11, 2001 and aftermath [169]
* World War II: Military service: 100th Infantry Battalion [421]
Not affected
* 522nd Field Artillery Battalion [90]
* World War II: Military service: 1800th Engineer General Service Battalion [221]

Several possibilities:
- Edit page view code or something in the models code.
- Tagmanager (jQuery tool that manages the topics and facilities fields.

**Comment by gjost** [comment] 2015-03-26 18:04
Quick test, and looks like the problem is in the view code.  The extra topic is present in the `topics_prefilled` var at the end of the view function.

**Comment by gjost** [comment] 2015-03-26 18:39
Fixed in 9705dcd3e1, merged into `master` in 2a6bd9a159.

**Closed by gjost** 2015-03-26 18:39 UTC
Labels: bug

**Comment by pkikawa** [comment] 2019-08-07 18:46
Reopening for regression. present in version 2.8.9 Master
